// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef FltkView_h
#define FltkView_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/gl.h>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_File_Chooser.H>
#include "FltkForm.h"

class GuiView {
public:
  GuiView();
  Fl_Double_Window *mainWindow;
  Fl_Menu_Bar *menu;
  static Fl_Menu_Item menu_menu[];
  static Fl_Menu_Item *file;
  static Fl_Menu_Item *open;
  static Fl_Menu_Item *quit;
  FltkForm *curve;
  void show();
  static void scb_open(Fl_Widget *o, void *v);
  static void scb_quit(Fl_Widget *o, void *v);
  void cb_menu_open();
};
#endif
